//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionICR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesTbl
    {
        public ActivitiesTbl()
        {
            this.NewsTbls = new HashSet<NewsTbl>();
        }
    
        public int ActivitiesID { get; set; }
        public string ActivitiesDesc { get; set; }
        public Nullable<int> EventID { get; set; }
        public string UserIdenfiticationNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual UserTbl UserTbl { get; set; }
        public virtual ICollection<NewsTbl> NewsTbls { get; set; }
    }
}
