//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionICR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPollingBooth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPollingBooth()
        {
            this.UserTbls = new HashSet<UserTbl>();
        }
    
        public Nullable<int> StateId { get; set; }
        public Nullable<int> LGAId { get; set; }
        public Nullable<int> WardId { get; set; }
        public string PollingBoothCode { get; set; }
        public string PollingBoothName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Address { get; set; }
        public int PollingBoothId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Delim { get; set; }
    
        public virtual tblLGA tblLGA { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblWard tblWard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTbl> UserTbls { get; set; }
    }
}
