//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionICR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTbl
    {
        public string UserIdenfiticationNumber { get; set; }
        public int UserID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Gender { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string PassportPhoto { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> OperationalLevelID { get; set; }
        public Nullable<int> UserCategoryID { get; set; }
        public string PhoneNumber { get; set; }
        public string IdentificationType { get; set; }
        public string MeansOfIdentification { get; set; }
        public string Occupation { get; set; }
        public string AgeRange { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> LGAId { get; set; }
        public string UserApprovalStatus { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<int> PollingBoothId { get; set; }
        public Nullable<int> NoHouseholdPeople { get; set; }
        public Nullable<int> NoHousePpleWithPVC { get; set; }
        public string HouseholdNeed1 { get; set; }
        public string HouseholdNeed2 { get; set; }
        public string HouseholdNeed3 { get; set; }
        public string HouseholdNeed4 { get; set; }
        public string HouseholdNeed5 { get; set; }
        public string MobilizerRep { get; set; }
        public string MobilizerRepCode { get; set; }
        public string LanguageSpoken1 { get; set; }
        public string LanguageSpoken2 { get; set; }
        public string LanguageSpoken3 { get; set; }
        public string Qualification { get; set; }
        public string EmploymentStatus { get; set; }
        public string RefererCode { get; set; }
        public Nullable<int> PreviousGroupId { get; set; }
        public Nullable<int> CurrentGroupId { get; set; }
        public string UserFirstPortfolio { get; set; }
        public string UserSecondPortfolio { get; set; }
        public Nullable<int> UserReferralCount { get; set; }
        public string VIN { get; set; }
    
        public virtual tblLGA tblLGA { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblWard tblWard { get; set; }
        public virtual tblPollingBooth tblPollingBooth { get; set; }
    }
}
